bug fixes

diff --git a/translate/pre-commit b/translate/pre-commit
--- a/translate/pre-commit
+++ b/translate/pre-commit
@@ -13,21 +13,23 @@
 # Auto-generate translated StartDSTwithParams using sed and predefined sed's rules
 #
 #
-CHANGED=$(git diff --name-only --cached --diff-filter=ACMR | grep -c "StartDSTwithParamsRus.cmd")
+fname_eng="StartDSTwithParamsEng.cmd"
+fname_rus="StartDSTwithParamsRus.cmd"
+CHANGED=$(git diff --name-only --cached --diff-filter=ACMR | grep -c -F "${fname_rus}")
 if  [ "$CHANGED" -ne "0" ]; then
     if [ -f StartDSTwithParamsEng.cmd ]; then
-        date_eng=$(stat -c "%Y" StartDSTwithParamsEng.cmd)
-        date_rus=$(stat -c "%Y" StartDSTwithParamsRus.cmd)
-        echo "date_eng: $date_eng\ndate_rus: $date_rus"
+        date_eng=$(date -r ${fname_eng} +%s)
+        date_rus=$(date -r ${fname_rus} +%s)
+        echo -n "'${fname_eng}' date/time modification: "
+        date -r ${fname_eng} +"%F  %X"
+        echo -n "'${fname_rus}' date/time modification: "
+        date -r ${fname_rus} +"%F  %X"
         if [ "$date_eng" -gt "$date_rus" ]; then
-            echo "Time of last modification StartDSTwithParamsEng greater than StartDSTwithParamsRus."
-            exit 1
+            echo -e "\nTime of last modification ${fname_eng} greater than ${fname_rus}.\n"
+            echo "Commit aborted."
+            exit 3
         fi
-    else
-        echo "StartDSTwithParamsEng.cmd not found"
     fi
-    sed -b -f translate/rus2en.sed StartDSTwithParamsRus.cmd > StartDSTwithParamsEng.cmd;
-    git add StartDSTwithParamsEng.cmd;
-else
-    echo "StartDSTwithParamsRus.cmd not changed"
+    sed -b -f translate/rus2en.sed ${fname_rus} > ${fname_eng};
+    git add $fname_eng;
 fi
